cors:
  originPatterns: "http://localhost:8080,http://localhost:3000,https://www.oracle.com/"
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_api_rest_aws?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: juliancambraia
    password: planet@123456
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: db_api_rest_aws
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    spring:
      flyway:
        baseline-on-migrate: true
        baseline-version: 0
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
