spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_api_rest_aws?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: planet@123456
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
